services:
 db:
  container_name: micro_mongodb
  image: mongo
  restart: always
 rabbitmq:
  container_name: micro_rabbitmq
  image: rabbitmq
  restart: always
 authentication:
  container_name: micro_authentication
  build: authentication
  depends_on:
   - db
   - rabbitmq
  restart: always
 user:
  container_name: micro_user
  build: user
  depends_on:
   - db
   - rabbitmq
  restart: always
 book:
  container_name: micro_book
  build: book
  depends_on:
   - db
   - rabbitmq
  restart: always
 transaction:
  container_name: micro_transaction
  build: transaction
  depends_on:
   - db
   - rabbitmq
  restart: always
 gateway:
  container_name: micro_gateway
  build: gateway
  ports:
    - 9000:9000
  depends_on:
    - user
    - transaction
    - book
    - authentication
  restart: always